import { Gem, Crown, Trophy, Star, Award } from "lucide-react";
import type { SponsorshipTier } from "./types";

export const sponsorshipTiers: SponsorshipTier[] = [
  {
    id: "naming-rights",
    name: "Naming Rights",
    price: 5000,
    icon: Gem,
    benefits: [
      "Naming rights to the club (on FB page, website, signage)",
      "Option for $14,000 over 3 years",
      "10 adult club memberships (valued at $150 each, can be swapped)",
      "10 tickets into Australian Open draw",
      "Tickets to Hobart & Launceston International",
      "A-frame courtside advertising for Tasmanian Championships",
      "Clubroom hire fee waived ($300)",
      "Free court hire (bookings essential)",
      "Annual Corporate Sponsor Day",
      "Sponsorship signage on streetfront",
      "Advertising in clubrooms, web page and Facebook",
      "Devonport Tennis Club merchandise",
      "Member prices at bar",
    ],
  },
  {
    id: "platinum",
    name: "Platinum",
    price: 2000,
    icon: Crown,
    benefits: [
      "5 adult club memberships (valued at $150 each)",
      "Clubroom hire fee waived ($300)",
      "5 tickets into Australian Open draw",
      "Tickets to Hobart & Launceston International",
      "A-frame courtside advertising for Tasmanian Championships",
      "Free court hire (bookings essential)",
      "Annual Corporate Sponsor Day",
      "Noticeboard advertising in Clubhouse",
      "Sponsorship signage on streetfront",
      "Advertising on web page and Facebook",
      "Devonport Tennis Club Merchandise",
      "Drink card / discounted drinks",
    ],
  },
  {
    id: "gold",
    name: "Gold",
    price: 1000,
    icon: Trophy,
    benefits: [
      "3 adult club memberships (valued at $150 each)",
      "Clubroom hire fee waived ($300)",
      "2 tickets into Australian Open draw",
      "Tickets to Hobart & Launceston International",
      "A-frame courtside advertising for Tasmanian Championships",
      "Free court hire (bookings essential)",
      "Annual Corporate Sponsor Day",
      "Noticeboard advertising in Clubhouse",
      "Sponsorship signage on streetfront",
      "Advertising on web page and Facebook",
      "Devonport Tennis Club Merchandise",
      "Drink card / discounted drinks",
    ],
  },
  {
    id: "silver",
    name: "Silver",
    price: 500,
    icon: Star,
    benefits: [
      "2 adult club memberships (valued at $150 each)",
      "Annual Corporate Sponsor Day",
      "Noticeboard advertising at Clubrooms",
      "Sponsorship signage",
      "Advertising in newsletter, web page and Facebook",
      "Devonport Tennis Club Merchandise",
      "Drink card / discounted drinks",
    ],
  },
  {
    id: "bronze",
    name: "Bronze",
    price: 300,
    icon: Award,
    benefits: [
      "Annual Corporate Sponsor Day",
      "Sponsorship signage either on Club or court",
    ],
  },
];
